var xa_messages_table = new Array(
 new Array("itemname", 0, "An error occured in input data : field [@].\n\n"),
 new Array("required", 0, "The field should not be empty. Please fill the field."),
 new Array("minlength", 0, "The length of the value is too short. \nIt should be more than @."),
 new Array("maxbyte", 0, "The length of the value is too long. \nIt should be less than @."),
 new Array("minbyte", 0, "The length of the value is too short. \nIt should be more than @."),
 new Array("maxbyte_utf8", 0, "The length of the value is too long. \nIt should be less than @."),
 new Array("minbyte_utf8", 0, "The length of the value is too short. \nIt should be more than @."),
 new Array("maxvalue", 0, "The value, [@] is too large. \nIt should be less than @."),
 new Array("minvalue", 0, "The value, [@] is too small. \nIt should be more than @."),
 new Array("alphabetic", 0, "It's not alphabetic. Please enter alphabet-only."),
 new Array("alpha_numeric", 0, "It's neither alphabetic nor numeric. Please enter alphanumeric-only."),
 new Array("numeric", 0, "It's not numeric. Please enter numeric-only."),
 new Array("money", 0, "It's not money-formatted. Please re-enter the value."),
 new Array("integer", 0, "It's not integer-formatted. Please re-enter the value."),
 new Array("float", 0, "It's not float-formatted. Please re-enter the value."),
 new Array("hexa", 0, "It's not hexa-formatted. Please re-enter the value."),
 new Array("is_value", 0, "xJos says :\nWrong usage of is_value() in [@]. \nCan't find an object such as [@]."),
 new Array("is_value", 1, "xJos says :\nWrong usage of is_value() in [@]. \nThere's no value in the object such as [@]."),
 new Array("is_value", 2, "[@]'s value does not match with [@]'s value."),
 new Array("mask", 0, "Invalid format. \nThe value should be matched with [@] format."),
 new Array("date", 0, "Please enter a valid date value."),
 new Array("psn", 0, "Please enter a valid Personal Registration Number."),
 new Array("csn", 0, "Please enter a valid Company Registration Number."),
 new Array("credit_card", 0, "Please enter a valid Credit Card Number."),
 new Array("email", 0, "Please enter a valid email address."),
 new Array("advanced_email", 0, "Please enter a valid email address."),
 new Array("advanced_email", 1, "Please enter a valid email address. \nThere is an invalid character in user name part."),
 new Array("advanced_email", 2, "Please enter a valid email address. \nThere is an invalid character in domain name part."),
 new Array("advanced_email", 3, "Please enter a valid email address. \nUser name is wrong."),
 new Array("advanced_email", 4, "Please enter a valid email address. \nIP address is wrong."),
 new Array("advanced_email", 5, "Please enter a valid email address. \nDomain name is wrong."),
 new Array("advanced_email", 6, "Please enter a valid email address. \nDomain name is not well-known."),
 new Array("advanced_email", 7, "Please enter a valid email address. \nThere's no host name."),
 new Array("domain", 0, "Please enter a valid domain address."),
 new Array("reg_exp", 0, "It doesn't match with regular expression. \nThe value should be suitable to @."),
 new Array("ddd", 0, "@ is not a right DDD prefix."),
 new Array("hpd", 0, "@ is not a right cellular phone prefix.")
);