var xa_messages_table = new Array(
 new Array("itemname", 0, "Input data error occured : field[@]\n\n"),
 new Array("required", 0, "required field. please fill data"),
 new Array("minlength", 0, "value is too short. \nvalue length should be more than @"),
 new Array("maxbyte", 0, "value is to long. \nvalue length should be less then @"),
 new Array("minbyte", 0, "value is to short. \nvalue length should be more than @"),
 new Array("maxbyte_utf8", 0, "value is to long. \nvalue length should be less then @)"),
 new Array("minbyte_utf8", 0, "value is to short. \nvalue length should be more than @"),
 new Array("maxvalue", 0, "value is to large. \ncurrent value is @. \nvalue should be less than @"),
 new Array("minvalue", 0, "value is to small. \ncurrent value is @. \nvalue should be more than @"),
 new Array("alphabetic", 0, "not alphabetic"),
 new Array("alpha_numeric", 0, "not alphabetic nor numeric"),
 new Array("numeric", 0, "not numeric"),
 new Array("money", 0, "not money type"),
 new Array("integer", 0, "not integer type"),
 new Array("float", 0, "not float type"),
 new Array("hexa", 0, "not hexa type"),
 new Array("is_value", 0, "xJos Says :\nwrong is_value useage in [@]. \ncann't found object such as [@]"),
 new Array("is_value", 1, "xJos Says :\nwrong is_value useage in [@]. \nthere is no value in object such as[@]"),
 new Array("is_value", 2, "[@]'s value is not match [@]'s value"),
 new Array("mask", 0, "format error.\nvalue should be match in [@] format"),
 new Array("date", 0, "date error"),
 new Array("psn", 0, "personal registration number error"),
 new Array("csn", 0, "company registration number error"),
 new Array("credit_card", 0, "not a Credit Card number"),
 new Array("email", 0, "not a email address"),
 new Array("advanced_email", 0, "not a email address"),
 new Array("advanced_email", 1, "email address format error. \ninvalid character in user name part"),
 new Array("advanced_email", 2, "email address format error. \ninvalid character in domain name part"),
 new Array("advanced_email", 3, "email address format error. \nwrong user name"),
 new Array("advanced_email", 4, "email address format error. \nwrog IP address"),
 new Array("advanced_email", 5, "email address format error. \nwrong Domain name"),
 new Array("advanced_email", 6, "email address format error. \nDomain name is not well known"),
 new Array("advanced_email", 7, "email address format error. \nno host name"),
 new Array("domain", 0, "domain address format error."),
 new Array("reg_exp", 0, "Does not match with Regular Expression. \Should suitable to @"),
 new Array("ddd", 0, "@ is not a right DDD prifix"),
 new Array("hpd", 0, "@ is not a right  cellular phone prefix")
);